# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2945e8755b83c6a4d94b27deaa40ab83085ca25f6bd3358a57f38e96522ac1a4a357a34e2875c29e585be9e5b1b643e252a9a3913170d739b49771366c504992

test:
  secret_key_base: 488bb83ba8d2b973abe4fd9806f3366ce4db8de210ae354d42201258560f7eeeeee5d23cecd98c9fdb298fa18d7e1650d3bcb732ca1357c21e9a58a428c882e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
